### ISSUE TITLE
Error in "_route_data(command, data.path, data.data)"

### ISSUE THREAD

**Issue by leandrodreamer** [WolfgangSenff/GodotFirebase#11]
in the function on_new_sse_event(headers, event, data): in FirebaseReference.gd "data" comes as an string, then data.path and data.data in _route_data(command, data.path, data.data) fails
i think that can be fixed just likle this: _route_data(command, parse_json(data).path, parse_json(data).data) or in HTTPSSEClient.gd emit_signal("new_sse_event", headers, event_data.event, parse_json(event_data.data)) (that is what i do)

**Comment by WolfgangSenff** [comment]
I believe this should already be fixed. I'm not sure why you're seeing it. Wondering if my submodule trickery didn't work the way I intended. Let me check and make sure.

**Comment by WolfgangSenff** [comment]
As best I can tell, this is already resolved. Please make sure you get latest and if it's still an issue, come back and re-report it. I'm going to close this for now.
