### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by MasterPolska123** [WolfgangSenff/GodotFirebase#14]
I had a few bugs:
1. When the account was registered, nothing happened and when I clicked the "Login" button
the "INVAILD_PASSWORD" error popped up, although I did not change anything :(.
2. How I managed to register (still in the login "INVAILD_PASSWORD" pops up) the "Assertion Failed" pops up in the debugger. After omitting this error, "Invalid get index 'event' appears (on base: 'Nil')."
All errors apply to the HTTPSSEClient.gd script

**Comment by WolfgangSenff** [comment]
That's odd. I'm not sure what's up with that, aside from the typo in "INVALID". :P I have had no issues with this though - can you provide reproduction steps precisely?

**Comment by MasterPolska123** [comment]
I do not have this error anymore. It seems that windows found that the internet below 1 mb / s is broken and for half an hour I did not really have any internrter, but the connection icon indicated that everything is ok.
