### ISSUE TITLE
Comments in scripts

### ISSUE THREAD

**Issue by MasterPolska123** [WolfgangSenff/GodotFirebase#16]
I have a request. Add comments to each function with examples for each argument. Otherwise. I do not understand in which argument to enter the file name / path of the file that I want to send / download from the Firebase Storage server. Would you be willing to write an example in the comment on how to send / download a file to / from Firebase Storage? I need this in my online scoreboard in game. And if you can, 'finish' it - #13

**Comment by BearDooks** [comment]
@MasterPolska123 , While it is not done yet I have been working to comment some of the code and write up some docs on how this plugin works. I just got some new items working and I am currently writing up the docs for it. Hopefully after it is done you can at least get this into your game and test it out

**Comment by MasterPolska123** [comment]
Thanks. It will be very helpful for me and other users.

czw., 21 lis 2019, 15:53 użytkownik Chuck <notifications@github.com>
napisał:

**Comment by WolfgangSenff** [comment]
A friend and I have gone through and added many comments. Hopefully they're helpful!
