### ISSUE TITLE
Any chance for FB and Twitter auth for Android and iOS?

### ISSUE THREAD

**Issue by japalekhin** [WolfgangSenff/GodotFirebase#21]
Hey, is there any chance for FB and Twitter sign in any time soon?

**Comment by WolfgangSenff** [comment]
This should already be supported - you just have to follow the setup instructions for (for example) Facebook found in the Authentication tab in the Firebase Console. Once you've completed that, login should work the same way - the login flow happens in the Firebase Auth backend, or so I understand it.

**Comment by japalekhin** [comment]
> Firebase Auth backend

ahh really? i'll check it out.

**Comment by japalekhin** [comment]
thanks, by the way!

**Comment by WolfgangSenff** [comment]
It should! If it doesn't, definitely please come back and put another issue in and I'll look into it. Everything I've found regarding it though says it all happens through Firebase auth, and not specifically Facebook/whatever auth. I think they just provide the logic behind-the-scenes to make it easier to use.
