### ISSUE TITLE
Demo project not immediately working

### ISSUE THREAD

**Issue by BabeleDunnit** [WolfgangSenff/GodotFirebase#28]
I am trying to run the demo project by cloning (I also correctly updated the HTTPSSEClient submodule in res://addons/GDFirebase/HTTPSSEClient) and scanning the folder. A project named TestFirebaseJS has been located. I initialized everything on Firebase and I am actually logging in and creating an user on Firebase, so it seems to work.

Immediately after the login/user creation I am getting an error "Invalid get index 'Storage' (on base: 'Node (Firebase.gd)')." at https://github.com/WolfgangSenff/GodotFirebase/blob/29839469e2ee0b2b0136b5ca0822cc03530c4b68/Demo/ChatControl.gd#L16 and in fact I do not see any ".Storage" symbol in Firebase.gd (but I am new on Godot/GDScript so this could be my fault). I then noticed that the two Firebase.gd files (https://github.com/WolfgangSenff/GodotFirebase/blob/master/GDFirebase/Firebase.gd vs https://github.com/WolfgangSenff/GodotFirebase/blob/master/Demo/addons/GDFirebase/Firebase.gd) are different, so I tried to overwrite the demo addons/GDIFirebase folder with the other, but still with no luck, same error.

is ChatControl.gd line 16 redundant because the var is already initialized with the correct type at line 5? commenting line 16 seems to work...

Took a while to get everything out (for example the need for submodule update, you should mention it, I tried by just copying the files from a download of the master and it was obviously broken), but all of this seems very interesting. You should do some release or at least tag some known-to-work master commit... Also, would be nice if the demo was aligned with the latest version of the library - again, using a git submodule? But I suppose you should split the repository in two, one with the lib and the other with the demo (never used submodules)...

Thanks, later

Aaron

**Comment by WolfgangSenff** [comment]
Submodules suck. I'm never using them again. Next time I'll find a better way to handle them.

Regarding the other bit, I'll check it out - I merged a PR when I didn't have the ability to double check the demo. Sorry about that. In fact, I'll likely just upload a proper demo, the current one is dumb. Leaving the open to remind me to do it when I have a chance. Thanks!

**Comment by BabeleDunnit** [comment]
I see. In the meanwhile, could you just just show me a commit before the mentioned merge where the demo was supposed to work? I would like to experiment a bit... thanks!

**Comment by WolfgangSenff** [comment]
Actually, there's a simple fix as far as I can tell. Unfortunately, my home computer just blew up (literally) and I'm not allowed to put Godot on my work computer, so I can't test this with absolute certainty, but someone else who was trying it found that if you go into the file you reference and simply delete that line, it works. I know he was able to login at least (and run of course)!

**Comment by WolfgangSenff** [comment]
Seems that was one place I missed when sanitizing my old code of Storage references. I'd attempted to implement it in the past, but after talking with the Firebase team, they deemed Firestore to not be performant enough for any real game purposes aside from, like, settings and what not, and that's not why I built this plugin, so I thought I'd removed it. But then someone sent me a PR and I was happy to accept, but I forgot to ensure the Demo was good to go, so my fault.

**Comment by WolfgangSenff** [comment]
I have updated the Demo to work properly.
