### ISSUE TITLE
Invalid call. Nonexistent function 'connect_to_host' in base 'Node'.

### ISSUE THREAD

**Issue by Nv7-GitHub** [WolfgangSenff/GodotFirebase#30]
When I tried to get a database reference, I get the error ```Invalid call. Nonexistent function 'size' in base 'bool'.```
I have placed no filters.
Godot version: 3.2.2, no mono support
Full error:
```
FirebaseReference.gd:119	if path == separator and data.size() > 0:
FirebaseReference.gd:61		_route_data(command, data.path, data.data)
HTTPSSEClient.gd:86 		emit_signal("new_sse_event", headers, event_data.event, result)
```

**Comment by WolfgangSenff** [comment]
Hm. What do you mean by you placed no filters? Did you pass an empty set of filters, i.e. {}, or null?

**Comment by martinpelli** [comment]
> Hm. What do you mean by you placed no filters? Did you pass an empty set of filters, i.e. {}, or null?

hi, can you explain what does this plugin do? I don´t inderstand step 4, I only want to connect firebase to my game on iOS  and Android

**Comment by insydeAFK** [comment]
> 
> 
> Hm. What do you mean by you placed no filters? Did you pass an empty set of filters, i.e. {}, or null?

Hi, do you will add AdMob, Ads, etc in future?.
Btw. great work! Thanks.

**Comment by WolfgangSenff** [comment]
@insydeAFK - Admob does not have a REST API as far as I know. One exists to do things like managing Admob statistics and crap like that, but nothing as far as I know to actually implement it on the platform, which is very painful. I definitely want to, but I keep lobbying them to create one and they won't.

**Comment by WolfgangSenff** [comment]
@martinpelli - There's a *picture* of what to do in step 4. If you don't know what the plugin does, it's best you go research Firebase to try to understand cloud-based databases and then come back, download it, and follow the instructions.

**Comment by insydeAFK** [comment]
> 
> 
> @insydeAFK - Admob does not have a REST API as far as I know. One exists to do things like managing Admob statistics and crap like that, but nothing as far as I know to actually implement it on the platform, which is very painful. I definitely want to, but I keep lobbying them to create one and they won't.

Can you help me how to get a document?
Without you plugin I have used: "Firebase.get_document("users/%s" % Firebase.user_info.id, http)"
How to do with your pulgin? Thanks.
