### ISSUE TITLE
How to set user display name?

### ISSUE THREAD

**Issue by WolfGames** [WolfgangSenff/GodotFirebase#35]
I want to change  user DisplayName
How?

bruh i dont know how to add label "help wanted" to this

**Comment by WolfgangSenff** [comment]
I'm not actually sure what you're asking. You mean from the Authentication call? Typically, you'd want them to put in their own display name so they can choose what they want; then, when they are Authenticated, you'd associate their user ID from the Authentication with the name they chose, store that in the Realtime Database, and use it from that point on: when they authenticate, you then go get their appropriate display name. This is not really a question for the plugin though.

**Comment by Invy55** [comment]
> I'm not actually sure what you're asking. You mean from the Authentication call? Typically, you'd want them to put in their own display name so they can choose what they want; then, when they are Authenticated, you'd associate their user ID from the Authentication with the name they chose, store that in the Realtime Database, and use it from that point on: when they authenticate, you then go get their appropriate display name. This is not really a question for the plugin though.

This answer doesn't stand out, as you can see there https://firebase.google.com/docs/reference/rest/auth?hl=en#section-update-profile there is a method that indeed does what the user originally asked. I would love to see it implemented, and I will do it for myself if needed.

**Comment by WolfgangSenff** [comment]
> > I'm not actually sure what you're asking. You mean from the Authentication call? Typically, you'd want them to put in their own display name so they can choose what they want; then, when they are Authenticated, you'd associate their user ID from the Authentication with the name they chose, store that in the Realtime Database, and use it from that point on: when they authenticate, you then go get their appropriate display name. This is not really a question for the plugin though.
> 
> This answer doesn't stand, as you can see there https://firebase.google.com/docs/reference/rest/auth?hl=en#section-update-profile there is a method that indeed does what the user originally asked. I would love to see it implemented, and I will do it for myself if needed.

 If you had just looked at @fenix-hub's PR conveniently linked, it shows it's already been implemented.
