### ISSUE TITLE
Refresh Token Missing

### ISSUE THREAD

**Issue by Zarasan** [WolfgangSenff/GodotFirebase#36]
I get missing refresh token after the login has timed out, how do I set it up so it refreshes while the application is opened?

**Comment by WolfgangSenff** [comment]
Hm. I would expect it to work already - it's possible there's a bug though. Thanks! I'll check it out.

**Comment by Zarasan** [comment]
Managed to fix it for me by updating refreshtoken fields, they should all be lowercase

![image](https://user-images.githubusercontent.com/43384612/96126993-8fa9a180-0ef4-11eb-8557-56492c238515.png)

**Comment by WolfgangSenff** [comment]
Doh. Okay. That's pretty ridiculous. I think it's something they changed - we have a thing which auto-lowercases every key in these responses. Mind opening a PR for this?
