### ISSUE TITLE
Confused the Databasing type between Realtime Database & Cloud Firestore

### ISSUE THREAD

**Issue by JOELwindows7** [WolfgangSenff/GodotFirebase#37]
Recontinue issue #33 ...

Oh. no..

![[It works if you setup Realtime Database](https://odysee.com/@JOELwindows7:a/oopsay-firebase-wolfgangsen-works-again:7?r=GywiacPEX6284FYr8og9R8FM4LbJ71AJ)](https://odysee.com/$/download/oopsay-firebase-wolfgangsen-works-again/7bf021f4787e386c7ee7ae60ddcc05323e1581ed)

# I've misunderstood this concept of this addon the whole time. I bet people had misunderstood this too. I think you should add instruction how to start the database which is Realtime Database, since Firebase has 2 types of Databasing (Cloud Firestore & Realtime Database.

Let me clarify:

-  This addon as you can see with the demo uses **Realtime Database**. Not to be confused with *Cloud Firestore*.
- Realtime Database uses References I mentioned earlier.
- So if you did not see the change coming right up in the databaser, it's not Cloud Firestore! it's Realtime Database!

# What did I do?
- I've compared between this addon and GDquest
- Yes, GDquest did not handle streamed updated. This one, updates something like Authentication key after certain times, as I saw in FirebaseAuth thingy, method `begin_refresh`
- I've read mentioned script you told. it seems that this demo nor the plugin itself no longer used some part of the script like one you mentioned anymore. tell me if I'm wrong. I've tried my best to figured which script loads which and did the script being loaded from that script; basically complexity. 
- I've read from issue #28 that the demo used to use something like Firebase Storage, wait. this is File hosting. nvm. idk.
- Wait, Firebase Storage script isn't referenced in the initialization `_ready()` on main Firebase.gd anymore? Haven't seen the node reference of Storage....
- I can only see `Firebase.Auth`, and `Firebase.Database` . that's it. where's the other? is it separately referenced out of `Firebase.gd`? it seems those unreferenced ones supposed to be referenced via `Firebase.gd` first beforehand, but it's absent `Firebase.Firestore`, `Firebase.Storage`, or whatever other. Because it had no self initialization `_ready` like to connect signals to parent node whom the node was instancing.
- Manually curl this back and forth, to make sure from other types of client.

# Curl I did in cmd.exe
https://firebase.google.com/docs/reference/rest/database?hl=en . I didn't know that I do is for Realtime Database
```
curl -X POST -d "{ \"first\": \"Jack\", \"last\": \"Sparrow\" }" "https://sandboxon-407f9.firebaseio.com/users/jack/name.json"
```
Above is when `Project-id.firebaseio.com` which is Realtime Databse

https://www.youtube.com/watch?v=-vDNk7BzOGc  
https://github.com/GDQuest/godot-demos/blob/master/2019/05-21-firebase-firestore/end/interface/profile/UserProfile.gd . I tried to manually makeshift the curl synthax to replicate the HTTPCLient's request. It did work if did in supposed way, but I couldn't figure out working synthax for cmd.exe.
```
curl -X POST -d {"fields":{"Crondle":{"stringValue":"JOELwindows7"}}} "https://firestore.googleapis.com/v1/projects/sandboxon-407f9/databases/(default)/documents/PlesWork/unadio10"
```
⚠ Command not work. Above is when `firestore.googleapis.com` which is cloud firestore.

# So what's the problem?
I confused the Databasing feature as Cloud Firestore as most Tutorials that covers it, implements Firebase database feature, prepares Cloud Firestore, while actually this Plugin did used Realtime Database instead, as in the demo and what Firebase.gd currently initialize.

Bellow this is when it finally works
![[It works if you setup Realtime Database](https://odysee.com/@JOELwindows7:a/oopsay-firebase-wolfgangsen-works-again:7?r=GywiacPEX6284FYr8og9R8FM4LbJ71AJ )](https://odysee.com/$/download/oopsay-firebase-wolfgangsen-works-again/7bf021f4787e386c7ee7ae60ddcc05323e1581ed )

What I supposed to do is to Setup Realtime Database from now.  
![[Oh, Realtime Database?](https://odysee.com/@JOELwindows7:a/realtime-databasa-wolfsengang:a?r=GywiacPEX6284FYr8og9R8FM4LbJ71AJ )](https://odysee.com/$/download/realtime-databasa-wolfsengang/a5a157fb583efe57a6f83c9c5bfac0e40ddc737b )

Instead of Cloud Firestore (Though you should prepare that too just in case needed later).  
![[I thought it uses this](https://odysee.com/@JOELwindows7:a/cloud-firestore-aaa-pusing:7?r=GywiacPEX6284FYr8og9R8FM4LbJ71AJ )](https://odysee.com/$/download/cloud-firestore-aaa-pusing/74b7afac17cd9856ae6ac051d8b13f82f0423fe6 )

Because the demo uses Realtime Database. oh, I didn't know that.

# Edit: Solutions
- Add steps to setup Realtime Database, so customer won't be confused which Databasing should be prepared
- Readd Cloud Firestore reference in Firebase.gd . It seems that it is absent or idk..
- more features idk

**Comment by JOELwindows7** [comment]
# Wait, so it uses Realtime Database?
always has been

**Comment by JOELwindows7** [comment]
added edit of solution, add realtime database preparation instruction, and support for more firebase features

**Comment by WolfgangSenff** [comment]
It has both Realtime Database and Firestore. I will make sure the documentation is updated to include how to use Firestore, but note that I do reference Database the entire time, and at no point do I reference Firestore. So the confusion was unfounded.

**Comment by JOELwindows7** [comment]
> It has both Realtime Database and Firestore. I will make sure the documentation is updated to include how to use Firestore, but note that I do reference Database the entire time, and at no point do I reference Firestore. So the confusion was unfounded.

oops. I did not saw that. Now I compared with the AssetLib version (on folder `/GDFirebase`. **It already had Firestore on it**, while the Demo one (`/Demo/addons/GDFirebase`) forgot Firestore.

**Comment by JOELwindows7** [comment]
Bonus Issue!

I tried firestore.

everytime to either Add or Update, you have to insert all your data inside
```
{
   "fields": data_whatever
}
```
which above went into parameter. It works and that means the methods did not append `fields` insertion, unlike with GDQuest tutorial, where it already conveniently inserted all push data inside `fields`. umm...

**Comment by fenix-hub** [comment]
Hi @JOELwindows7 ,
Since I contributed to this plugin, and I still plan to contribute, just wanted to tell that the stuff you are reporting as "issues" are not actual issues whatsoever.

For your specific needings, the way you can resolve the "issue you are having" is just using the methods explicited and provided by this plugin:
1. Supposing you want to register a new user, build up a dictionary for it:  
```
var client : Dictionary = {
	"local_id":		AppDatabase.user.local_id,
	"display_name":	name+" "+surname,
	"telefono":	phone,
	"email":		email,
	"avatar":		"",
	}
```
2. Let's get a collection representing, for example, our clients
```
 var client_colletion : FirestoreCollection = Firebase.Firestore.collection("clients")
``` 
3. And let's create a FirestoreDocument object to do some parsing operations
```
 var firestore_doc : FirestoreDocument = FirestoreDocument.new()
``` 
4. Now we can register a new user adding a new document to our collection
```
 client_collection.add(userData.local_id, firestore_doc.dict2fields(client))
``

As you can see, we are using a method called `dict2fields`, which is a public method provided by the `FirestoreDocument` class.  
I wrote this parser to let developers who use GDScript to make faster `fields` colletions which are used by Firebase to fetch and parse datas.
How does it work? Very simple, just look for the function itself inside the FirestoreDocument class :)

Of course you could always do the whole process adding the `fields` key inside your dictionary, but you would need to follow the long format that Firebase itself requires. Anyway, you could notice this just CTRL+Clicking on the `add()` method: no `fields` key  used inside that function, so it needs to be used somewhere before. But in any case, this plugin **does not work** in the same way as the GDQuest one, so I find it really hard to compare the things. Taking it as a reference would just be missleading (and it is).

You see, as all the previous things you talked about, they are not themselves "issues", It is just a lack of documentation by us (which I'm aware of and admit, since it is a time-consuming task) but also a lack of plugin knowledge/usage by you.  
Don't take it personally: of course you are trying to do the things you need to do in the way you know, but as you already can see each thing you note is not an issue but just a feature you are experimenting and you resolve yourself.  
You are currently trying to do some stuff using another whole project as a reference (the GDQuest tutorial) and applying what you see there in another environment (this plugin), which uses different rules and concepts.  
It's a little bit like using Angular and pretend to do the same methods and procedures with React, and then go to the React forum opening some issues if stuff doesn't work.  
As I said, I'm not here to lecture you, it's just that you are making really big comments on stuff that just works, but you don't know the way.  
For what concern us and me personally, I'll make sure to work on some examples and a documentation which will explain the feature this plugin offers, and how you can solve very generic tasks that you could have to deal with in Firebase, using this plugin.
But please, don't make new issues for things you just don't know how they work. Instead, just contact us and we will explain you everything to make things clearer: its our job! :) 
Just make issues when you find a real bug, or something that *is not working the way Firebase is intended to work*.
Thank you very much.
