### ISSUE TITLE
Integration Question

### ISSUE THREAD

**Issue by shadowdraon319** [WolfgangSenff/GodotFirebase#49]
Does this work for iOS? Also do the analytics work? Looking for something that would track conversion events for installs from Google Ads.

**Comment by WolfgangSenff** [comment]
It does work for iOS, but analytics do not work yet. They are planned as best we can support them for the new year though. :) Thanks for your question! I'll leave this open briefly, until we've added this info into the wiki.

**Comment by WolfgangSenff** [comment]
Okay - I've added a lot more information to the wiki. Thanks for opening the issue - feel free to open another if you have more questions. At the moment, we cannot support Firebase Analytics directly because they do not have a REST API. Ads also do not support a REST API, unfortunately.
