### ISSUE TITLE
Video for instalation, make DataBase, call, and recoverdata !!

### ISSUE THREAD

**Issue by esbvaGames** [WolfgangSenff/GodotFirebase#8]
Hello:
        Please put a video, by all steps, for instalations, make database, and recover data, chat, analitics, etc !!!

thanks !!!

**Comment by WolfgangSenff** [comment]
It's coming soon! I'm going to be working with Pigdev on a couple videos showing how to use everything, including setup from the very beginning. However, analytics aren't supported yet. Everything else will be great. :)
