### ISSUE TITLE
HTTPSSEClient Assertion failed.

### ISSUE THREAD

**Issue by Winprox** [WolfgangSenff/GodotFirebase#9]
Hey, I am getting on "Assertion failed." error after trying to "get_database_reference".

![image](https://user-images.githubusercontent.com/16071244/58088980-7a7bf680-7bcc-11e9-8153-700b9e3d5cbf.png)

UPD: It was purely a Firebase related issue.

**Comment by salihkallai** [comment]
How to fix it?

**Comment by Winprox** [comment]
It was due to my Firebase Relatime Database Rules. To check if your issue is the same try debugging response you are getting from Firebase. In my case it was Permission Denied.
